build: false

environment:
  matrix:
    - PYTHON: C:\Python34
    - PYTHON: C:\Python34-x64

#matrix:
#  fast_finish: true 

init:
  - "ECHO %PYTHON%"
#  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"


install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts"
  - python -V
  - pip install nose numpy
  
test_script:
  - nosetests
  
  
