environment:
  matrix:
#    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64


init:
  - "ECHO %PYTHON%"
  - set PATH=C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python -V
  - python3 -V
  - where python  
  - where pip
  - python3 -m pip install --upgrade pip  
  - pip install numpy scipy pandas matplotlib nose scikit-learn graphviz

install:
  - "git clone --recursive https://github.com/dmlc/xgboost"
  - "cd xgboost"
  - git submodule init
  - git submodule update
  - mkdir build_mingw
  - cd build_mingw
  - cmake .. -G"Unix Makefiles"
  - make -j2  
  - cd %APPVEYOR_BUILD_FOLDER%\xgboost\python-package
  - python setup.py install  

test_script:
  - echo 'OK'


  
