image: Visual Studio 2013

#build: false

environment:
  matrix:
#    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64


init:
  - "ECHO %PYTHON%"
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -V
#  - pip install nose numpy


install:
  - "git clone --recursive https://github.com/dmlc/xgboost"
  - "cd xgboost"
  - git submodule init
  - git submodule update
  - mkdir build_mingw
  - cd build_mingw
  - cmake .. -G"Unix Makefiles"
  - make -j2  
  - cd %APPVEYOR_BUILD_FOLDER%\xgboost\python-package
  - python setup.py install  
#  - mkdir build
#  - cd build
#  - cmake .. -G"Visual Studio 12 2013 Win64"
#  - alias make='mingw32-make'
#  - cp make/mingw64.mk config.mk
#  - make -j4
#  - "%PYTHON%/Scripts/pip.exe install nose"
#  - "%PYTHON%/Scripts/pip.exe install coverage"

test_script:
  - echo 'OK'
#  - "%PYTHON%/Scripts/nosetests"

